# Generated by Django 5.2.9 on 2025-12-25 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_color_size_productfeature_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest_width', models.CharField(blank=True, max_length=50, verbose_name='عرض سینه')),
                ('length', models.CharField(blank=True, max_length=50, verbose_name='قد لباس')),
                ('sleeve_length', models.CharField(blank=True, max_length=50, verbose_name='دور آستین')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_charts', to='store.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.size')),
            ],
        ),
    ]
