"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-43i*fm9*v-sam#@%=x1)9(=^iw-v&kxil3%j*hbp86u452a0jj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'store',
    'cart',
    'orders',
    'accounts',
    'coupons',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# تنظیمات پنل مدیریت Jazzmin
JAZZMIN_SETTINGS = {
    # عنوان سایت (توی تب مرورگر)
    "site_title": "فربد بوتیک",
    
    # تیتر بالای صفحه لاگین
    "site_header": "مدیریت فربد بوتیک",
    
    # لوگوی سایت (اگر فایلش رو داری آدرس بده، فعلا متن نشون میدیم)
    "site_logo": None,
    
    # متن خوش‌آمدگویی در صفحه لاگین
    "welcome_sign": "به پنل مدیریت فربد بوتیک خوش آمدید",
    
    # کپی‌رایت پایین صفحه
    "copyright": "Farbod Boutique Ltd",
    
    # مدل‌هایی که میخوای تو صفحه اصلی سرچ بشن
    "search_model": ["store.Product", "auth.User", "orders.Order"],

    # لینک‌های منوی بالا
    "topmenu_links": [
        {"name": "خانه",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "مشاهده سایت", "url": "/"},
    ],

    # دسته‌بندی اپ‌ها (ترتیب نمایش)
    "order_with_respect_to": ["store", "orders", "accounts", "auth"],

    # آیکون‌های منوی سمت راست (از فونت‌آیکون‌های FontAwesome استفاده میکنه)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "store.Product": "fas fa-tshirt", # آیکون لباس
        "store.Category": "fas fa-list",
        "orders.Order": "fas fa-shopping-bag", # آیکون خرید
    },
    
    # فعال کردن دکمه تغییر تم (خیلی باحاله!)
    "show_ui_builder": True,
}

# تنظیمات ظاهری (تم تیره و جذاب)
JAZZMIN_UI_TWEAKS = {
    "theme": "darkly",   # تم تیره (می‌تونی عوضش کنی)
    "dark_mode_theme": "darkly",
}